<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['auth:admin', 'superadmin'])->prefix('superadmin')->group(function () {
    Route::get('/', [\App\Http\Controllers\Superadmin\DashboardController::class, 'index'])->name('superadmin.dashboard');
    Route::get('/rooms/page', [\App\Http\Controllers\Superadmin\PageController::class, 'rooms'])->name('superadmin.rooms.page');
    Route::get('/rooms', [\App\Http\Controllers\Superadmin\RoomController::class, 'index'])->name('superadmin.rooms.index');
    Route::post('/rooms', [\App\Http\Controllers\Superadmin\RoomController::class, 'store'])->name('superadmin.rooms.store');
    Route::get('/rooms/{room}/page', [\App\Http\Controllers\Superadmin\PageController::class, 'room'])->name('superadmin.rooms.detail.page');
    Route::get('/rooms/{room}', [\App\Http\Controllers\Superadmin\RoomController::class, 'show'])->name('superadmin.rooms.show');
    Route::match(['put', 'patch'], '/rooms/{room}', [\App\Http\Controllers\Superadmin\RoomController::class, 'update'])->name('superadmin.rooms.update');
    Route::patch('/rooms/{room}/status', [\App\Http\Controllers\Superadmin\RoomController::class, 'status'])->name('superadmin.rooms.status');
    Route::get('/admins/page', [\App\Http\Controllers\Superadmin\PageController::class, 'admins'])->name('superadmin.admins.page');
    Route::get('/admins', [\App\Http\Controllers\Superadmin\AdminController::class, 'index'])->name('superadmin.admins.index');
    Route::post('/admins', [\App\Http\Controllers\Superadmin\AdminController::class, 'store'])->name('superadmin.admins.store');
    Route::get('/admins/{admin}/page', [\App\Http\Controllers\Superadmin\PageController::class, 'admin'])->name('superadmin.admins.detail.page');
    Route::get('/admins/{admin}', [\App\Http\Controllers\Superadmin\AdminController::class, 'show'])->name('superadmin.admins.show');
    Route::match(['put', 'patch'], '/admins/{admin}', [\App\Http\Controllers\Superadmin\AdminController::class, 'update'])->name('superadmin.admins.update');
    Route::patch('/admins/{admin}/status', [\App\Http\Controllers\Superadmin\AdminController::class, 'status'])->name('superadmin.admins.status');
    Route::patch('/admins/{admin}/role', [\App\Http\Controllers\Superadmin\AdminController::class, 'role'])->name('superadmin.admins.role');
    Route::put('/admins/{admin}/rooms', [\App\Http\Controllers\Superadmin\AdminController::class, 'rooms'])->name('superadmin.admins.rooms');
    Route::post('/admins/{admin}/reset-password', [\App\Http\Controllers\Superadmin\AdminController::class, 'resetPassword'])->name('superadmin.admins.reset-password');
    Route::delete('/admins/{admin}', [\App\Http\Controllers\Superadmin\AdminController::class, 'destroy'])->name('superadmin.admins.destroy');
    Route::get('/global-users/page', [\App\Http\Controllers\Superadmin\PageController::class, 'users'])->name('superadmin.global-users.page');
    Route::get('/global-users', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'index'])->name('superadmin.global-users.index');
    Route::get('/global-users/{globalUser}/page', [\App\Http\Controllers\Superadmin\PageController::class, 'user'])->name('superadmin.global-users.detail.page');
    Route::get('/global-users/{globalUser}', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'show'])->name('superadmin.global-users.show');
    Route::patch('/global-users/{globalUser}/status', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'status'])->name('superadmin.global-users.status');
    Route::delete('/global-users/{globalUser}/memberships/{roomUser}', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'removeMembership'])->name('superadmin.global-users.memberships.remove');
    Route::post('/global-users/{globalUser}/memberships/{roomUser}/devices/{device}/revoke', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'revokeDevice'])->name('superadmin.global-users.devices.revoke');
    Route::post('/global-users/merge', [\App\Http\Controllers\Superadmin\GlobalUserController::class, 'merge'])->name('superadmin.global-users.merge');
    Route::get('/campaigns/page', [\App\Http\Controllers\Superadmin\PageController::class, 'campaigns'])->name('superadmin.campaigns.page');
    Route::get('/campaigns', [\App\Http\Controllers\Superadmin\CampaignController::class, 'index'])->name('superadmin.campaigns.index');
    Route::post('/campaigns/{campaign}/force-close', [\App\Http\Controllers\Superadmin\CampaignController::class, 'forceClose'])->name('superadmin.campaigns.force-close');
    Route::post('/campaigns/{campaign}/force-cancel', [\App\Http\Controllers\Superadmin\CampaignController::class, 'forceCancel'])->name('superadmin.campaigns.force-cancel');
    Route::get('/debts/page', [\App\Http\Controllers\Superadmin\PageController::class, 'debts'])->name('superadmin.debts.page');
    Route::get('/debts', [\App\Http\Controllers\Superadmin\DebtController::class, 'index'])->name('superadmin.debts.index');
    Route::get('/debts/export', [\App\Http\Controllers\Superadmin\DebtController::class, 'export'])->name('superadmin.debts.export');
    Route::get('/notifications/page', [\App\Http\Controllers\Superadmin\PageController::class, 'notifications'])->name('superadmin.notifications.page');
    Route::get('/notifications', [\App\Http\Controllers\Superadmin\NotificationController::class, 'index'])->name('superadmin.notifications.index');
    Route::post('/notifications', [\App\Http\Controllers\Superadmin\NotificationController::class, 'store'])->name('superadmin.notifications.store');
    Route::match(['put', 'patch'], '/notifications/{channel}', [\App\Http\Controllers\Superadmin\NotificationController::class, 'update'])->name('superadmin.notifications.update');
    Route::delete('/notifications/{channel}', [\App\Http\Controllers\Superadmin\NotificationController::class, 'destroy'])->name('superadmin.notifications.destroy');
    Route::get('/system/page', [\App\Http\Controllers\Superadmin\PageController::class, 'system'])->name('superadmin.system.page');
    Route::get('/system', [\App\Http\Controllers\Superadmin\SystemController::class, 'index'])->name('superadmin.system.index');
    Route::put('/system/settings', [\App\Http\Controllers\Superadmin\SystemController::class, 'settings'])->name('superadmin.system.settings');
    Route::get('/system/maintenance', [\App\Http\Controllers\Superadmin\SystemController::class, 'maintenance'])->name('superadmin.system.maintenance');
    Route::put('/system/maintenance', [\App\Http\Controllers\Superadmin\SystemController::class, 'maintenance'])->name('superadmin.system.maintenance.update');
    Route::post('/system/reset', [\App\Http\Controllers\Superadmin\SystemController::class, 'reset'])->name('superadmin.system.reset');
    Route::get('/audit-logs/page', [\App\Http\Controllers\Superadmin\PageController::class, 'audit'])->name('superadmin.audit.page');
    Route::get('/audit-logs', [\App\Http\Controllers\Superadmin\AuditController::class, 'index'])->name('superadmin.audit-logs.index');
    Route::get('/security-events/page', [\App\Http\Controllers\Superadmin\PageController::class, 'security'])->name('superadmin.security.page');
    Route::get('/security-events', [\App\Http\Controllers\Superadmin\SecurityController::class, 'index'])->name('superadmin.security-events.index');
    Route::get('/socket/page', [\App\Http\Controllers\Superadmin\PageController::class, 'socket'])->name('superadmin.socket.page');
    Route::get('/socket', [\App\Http\Controllers\Superadmin\SocketMonitoringController::class, 'index'])->name('superadmin.socket.index');
    Route::get('/socket-token', \App\Http\Controllers\Superadmin\SocketTokenController::class)->name('superadmin.socket-token');
    Route::get('/queue/page', [\App\Http\Controllers\Superadmin\PageController::class, 'queue'])->name('superadmin.queue.page');
    Route::get('/queue/failed', [\App\Http\Controllers\Superadmin\QueueController::class, 'index'])->name('superadmin.queue.failed.index');
    Route::post('/queue/failed/{failedJob}/retry', [\App\Http\Controllers\Superadmin\QueueController::class, 'retry'])->name('superadmin.queue.failed.retry');
    Route::delete('/queue/failed/{failedJob}', [\App\Http\Controllers\Superadmin\QueueController::class, 'forget'])->name('superadmin.queue.failed.forget');
    Route::get('/versions/page', [\App\Http\Controllers\Superadmin\PageController::class, 'versions'])->name('superadmin.versions.page');
    Route::get('/versions', [\App\Http\Controllers\Superadmin\VersionController::class, 'index'])->name('superadmin.versions.index');
    Route::post('/versions', [\App\Http\Controllers\Superadmin\VersionController::class, 'store'])->name('superadmin.versions.store');
    Route::match(['put', 'patch'], '/versions/{version}', [\App\Http\Controllers\Superadmin\VersionController::class, 'update'])->name('superadmin.versions.update');
    Route::delete('/versions/{version}', [\App\Http\Controllers\Superadmin\VersionController::class, 'destroy'])->name('superadmin.versions.destroy');
});
