@extends('superadmin.layout', ['title' => 'Global System Dashboard', 'active' => 'dashboard'])

@section('content')
<div class="superadmin-heading"><div><p class="superadmin-eyebrow">Core System · Live telemetry</p><h1>Global System Dashboard</h1><p>Giám sát hạ tầng, multi-room, hàng đợi và an ninh vận hành DrinkFlow trên toàn doanh nghiệp.</p></div><div class="superadmin-actions"><a class="sa-button secondary" href="{{ route('superadmin.socket.page') }}"><span class="material-symbols-outlined">hub</span>Live monitoring</a><a class="sa-button" href="{{ route('superadmin.system.page') }}"><span class="material-symbols-outlined">build_circle</span>System settings</a></div></div>
<div id="notice" class="sa-notice"></div>
<section class="sa-grid kpis">
    <article class="sa-card sa-kpi"><span class="label">Total Rooms</span><strong id="total-rooms" class="value">—</strong><span id="active-rooms" class="hint">Đang tải...</span></article>
    <article class="sa-card sa-kpi"><span class="label">Global Users</span><strong id="total-users" class="value">—</strong><span id="active-users" class="hint">Đang tải...</span></article>
    <article class="sa-card sa-kpi"><span class="label">Admins</span><strong id="total-admins" class="value">—</strong><span class="hint">Quản trị toàn hệ thống</span></article>
    <article class="sa-card sa-kpi"><span class="label">Orders Today</span><strong id="orders-today" class="value">—</strong><span class="hint">Đơn không bị hủy</span></article>
    <article class="sa-card sa-kpi"><span class="label">Outstanding Debt</span><strong id="debt" class="value">—</strong><span class="hint">Tổng công nợ còn lại</span></article>
</section>
<div class="sa-split"><section class="sa-card sa-section"><div class="sa-section-header"><div><h2>System health</h2><p>Trạng thái các lớp hạ tầng chính.</p></div><span class="status-pill status-ok"><span class="status-dot"></span>Telemetry</span></div><div class="sa-health-list"><div class="sa-health-row"><div><strong>Database</strong><small id="database-status">Checking...</small></div><span class="material-symbols-outlined">database</span></div><div class="sa-health-row"><div><strong>Queue</strong><small id="queue-status">Checking...</small></div><span class="material-symbols-outlined">sync_alt</span></div><div class="sa-health-row"><div><strong>Socket.IO</strong><small id="socket-status">Checking...</small></div><span class="material-symbols-outlined">hub</span></div></div></section><section class="sa-card sa-section"><div class="sa-section-header"><div><h2>Quick access</h2><p>Các khu vực cần theo dõi.</p></div></div><div class="sa-health-list"><a class="sa-health-row" href="{{ route('superadmin.security.page') }}"><div><strong>Security Center</strong><small>Failed login và security events</small></div><span class="material-symbols-outlined">arrow_forward</span></a><a class="sa-health-row" href="{{ route('superadmin.audit.page') }}"><div><strong>Global Audit Trail</strong><small>Lịch sử thay đổi toàn cục</small></div><span class="material-symbols-outlined">arrow_forward</span></a><a class="sa-health-row" href="{{ route('superadmin.queue.page') }}"><div><strong>Failed Jobs</strong><small>Retry hoặc xóa job lỗi</small></div><span class="material-symbols-outlined">arrow_forward</span></a></div></section></div>
@endsection

@push('scripts')
<script>
dfApi('{{ route('superadmin.dashboard') }}').then(({data}) => { document.querySelector('#total-rooms').textContent=data.total_rooms; document.querySelector('#active-rooms').textContent=`${data.active_rooms} room đang hoạt động`; document.querySelector('#total-users').textContent=data.total_global_users; document.querySelector('#active-users').textContent=`${data.active_global_users} user active`; document.querySelector('#total-admins').textContent=data.total_admins; document.querySelector('#orders-today').textContent=data.orders_today; document.querySelector('#debt').textContent=money(data.outstanding_debt); document.querySelector('#database-status').textContent=data.system_health.database; document.querySelector('#queue-status').textContent=`${data.queue_health.connection} · ${data.queue_health.failed_jobs} failed`; document.querySelector('#socket-status').textContent=data.socket_connections.status; }).catch(error => { const n=document.querySelector('#notice'); n.textContent=error.message; n.className='sa-notice error is-visible'; });
</script>
@endpush
