@extends('superadmin.layout', ['title' => 'System Settings & Maintenance', 'active' => 'system'])
@section('content')
<div class="superadmin-heading"><div><p class="superadmin-eyebrow">Infra &amp; Security</p><h1>System Settings &amp; Maintenance</h1><p>Cấu hình authentication cấp hệ thống, giới hạn mặc định và chế độ bảo trì.</p></div></div><div id="notice" class="sa-notice"></div><div class="sa-split"><section class="sa-card sa-section"><div class="sa-section-header"><div><h2>Maintenance mode</h2><p>Bật ngay hoặc lập lịch theo timezone hệ thống.</p></div></div><form id="maintenance-form" class="sa-health-list"><label class="sa-health-row"><span><strong>Enable maintenance</strong><small>Superadmin vẫn được truy cập.</small></span><input id="maintenance-enabled" type="checkbox"></label><label>Starts at<input id="maintenance-starts" class="sa-input" type="datetime-local"></label><label>Ends at<input id="maintenance-ends" class="sa-input" type="datetime-local"></label><button class="sa-button" type="submit">Save maintenance</button></form></section><section class="sa-card sa-section"><div class="sa-section-header"><div><h2>Typed settings</h2><p>Secret chỉ hiển thị trạng thái configured.</p></div></div><div id="settings-list" class="sa-health-list"></div></section></div><section class="sa-card sa-section"><div class="sa-section-header"><div><h2>Danger zone</h2><p>System reset xóa dữ liệu vận hành và giữ lại superadmin.</p></div></div><button class="sa-button danger" onclick="resetSystem()">Reset DrinkFlow</button></section>
@endsection
@push('scripts')
<script>
const systemNotice=(message,type='success')=>{const n=document.querySelector('#notice');n.textContent=message;n.className=`sa-notice ${type} is-visible`;};async function loadSystem(){const {data}=await dfApi('{{ route('superadmin.system.index') }}');document.querySelector('#maintenance-enabled').checked=data.maintenance.enabled;document.querySelector('#settings-list').innerHTML=data.settings.length?data.settings.map(s=>`<div class="sa-health-row"><div><strong>${escapeHtml(s.key)}</strong><small>${s.is_secret?'Secret · ':''}${s.configured?'Configured':'Not configured'}</small></div><span>${s.is_secret?'••••••••':' '+escapeHtml(s.value??'—')}</span></div>`).join(''):'<div class="sa-empty">Chưa có system setting.</div>';};document.querySelector('#maintenance-form').addEventListener('submit',async e=>{e.preventDefault();try{await dfApi('{{ route('superadmin.system.maintenance.update') }}',{method:'PUT',body:{enabled:document.querySelector('#maintenance-enabled').checked,starts_at:document.querySelector('#maintenance-starts').value||null,ends_at:document.querySelector('#maintenance-ends').value||null}});systemNotice('Đã lưu maintenance settings.');}catch(error){systemNotice(error.message,'error');}});async function resetSystem(){const password=prompt('Nhập mật khẩu superadmin');if(!password)return;const phrase=prompt('Nhập chính xác RESET DRINKFLOW');if(!phrase)return;if(!confirm('Thao tác này không thể hoàn tác. Tiếp tục?'))return;try{await dfApi('{{ route('superadmin.system.reset') }}',{method:'POST',body:{password,phrase}});systemNotice('Đã reset hệ thống.');}catch(error){systemNotice(error.message,'error');}}loadSystem();
</script>
@endpush
