@extends('superadmin.layout', ['title' => __('superadmin.users.title'), 'active' => 'users'])
@section('content')
<div class="superadmin-heading"><div><p class="superadmin-eyebrow">{{ __('superadmin.common.identity_layer') }}</p><h1>{{ __('superadmin.users.title') }}</h1><p>{{ __('superadmin.users.description') }}</p></div></div>
<div id="notice" class="sa-notice"></div>
<section class="sa-card sa-section"><div class="sa-section-header"><div><h2>{{ __('superadmin.users.global_users') }}</h2><p>{{ trans_choice('superadmin.common.global_users_count', $users->total(), ['count' => $users->total()]) }}</p></div><form method="get" class="sa-filters"><input name="q" class="sa-input" value="{{ request('q') }}" placeholder="{{ __('superadmin.users.search') }}"><button class="sa-button secondary">{{ __('superadmin.common.filter') }}</button></form></div>
<div class="sa-table-wrap"><table class="sa-table"><thead><tr><th>{{ __('superadmin.common.user') }}</th><th>{{ __('superadmin.users.oauth') }}</th><th>{{ __('superadmin.users.memberships') }}</th><th>{{ __('superadmin.common.status') }}</th><th>{{ __('superadmin.common.actions') }}</th></tr></thead><tbody>
@forelse($users as $user)<tr><td><strong>{{ $user->name }}</strong><br><small>{{ $user->email }}</small></td><td>{{ $user->oauthIdentities->pluck('provider')->join(', ') ?: '—' }}</td><td>{{ $user->room_users_count }}</td><td>{{ $user->status?->value ?? $user->status }}</td><td><div class="superadmin-actions"><a class="sa-button secondary" href="{{ route('superadmin.global-users.detail.page', $user) }}">{{ __('superadmin.common.details') }}</a><button class="sa-button danger" onclick="setUserStatus({{ $user->id }}, '{{ ($user->status?->value ?? $user->status) === 'blocked' ? 'active' : 'blocked' }}')">{{ ($user->status?->value ?? $user->status) === 'blocked' ? __('superadmin.common.unblock') : __('superadmin.common.block') }}</button><button class="sa-button danger" onclick="deleteUser({{ $user->id }})">{{ __('superadmin.common.delete') }}</button></div></td></tr>@empty<tr><td colspan="5" class="sa-empty">{{ __('superadmin.users.no_results') }}</td></tr>@endforelse
</tbody></table><div class="mt-4">{{ $users->withQueryString()->links() }}</div></div></section>
@endsection
@push('scripts')<script>
const userNotice=(message,type='success')=>{const n=document.querySelector('#notice');n.textContent=message;n.className=`sa-notice ${type} is-visible`;};
async function deleteUser(id){if(!confirm(@json(__('superadmin.users.confirm_delete'))))return;try{await dfApi(`/superadmin/global-users/${id}`,{method:'DELETE'});userNotice(@json(__('superadmin.users.deleted')));window.location.reload();}catch(e){userNotice(e.message,'error');}}
async function setUserStatus(id,status){try{await dfApi(`/superadmin/global-users/${id}/status`,{method:'PATCH',body:{status}});userNotice(@json(__('superadmin.users.status_updated')));window.location.reload();}catch(e){userNotice(e.message,'error');}}
</script>@endpush
