<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * What a platform invoice bills.
 *
 * `subscription` invoices a period of the running subscription (generated by billing:generate-invoices).
 * `upgrade` is requested by the Agent to move to a bigger package: the new package is only applied once
 * this invoice is fully paid, and an unpaid one simply expires instead of becoming overdue.
 */
enum InvoiceType: string
{
    case Subscription = 'subscription';
    case Upgrade = 'upgrade';
}
